// weather
export const WEATHER_API_LOADING = 'WEATHER_API_LOADING';
export const WEATHER_API_SUCCESS = 'WEATHER_API_SUCCESS';
export const WEATHER_API_FAILURE = 'WEATHER_API_FAILURE';

// sagas
export const REQUEST_WEATHER_INFO = 'REQUEST_WEATHER_INFO';